---
title: "C28163"
ms.custom: na
ms.date: "10/03/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: na
ms.suite: na
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: na
ms.topic: "article"
f1_keywords: 
  - "C28163"
helpviewer_keywords: 
  - "C28163"
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
caps.latest.revision: 3
ms.author: "douge"
manager: "douge"
translation.priority.ht: 
  - "de-de"
  - "es-es"
  - "fr-fr"
  - "it-it"
  - "ja-jp"
  - "ko-kr"
  - "ru-ru"
  - "zh-cn"
  - "zh-tw"
translation.priority.mt: 
  - "cs-cz"
  - "pl-pl"
  - "pt-br"
  - "tr-tr"
---
# C28163
warning C28163: The function should never be called from within a try/except block  
  
 This warning is reported when a function is of a type that should never be enclosed in a `try/except`  block is found in a `try/except` block. The code analysis tool found at least one path in which the function called was within a `try/except` block.